### ISSUE TITLE
Generated Ruby code ignores inheritance hierarchies

### ISSUE THREAD

**Issue by cshupp1** [stoicflame/enunciate#334]
Suppose I have the following start of a java class:

```
/**
 * Note that this is an abstract base class.  The actual returned type will be one of the
 * concrete subtype classes, such as {@link RestSememeDescriptionVersion} or {@link RestDynamicSememeVersion}
 */
@XmlSeeAlso ({RestSememeDescriptionVersion.class, RestDynamicSememeVersion.class, RestSememeLogicGraphVersion.class})
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY)
@XmlRootElement
public abstract class RestSememeVersion 
```
Further, suppose I have a Java class called  'RestSememeChronology' with the following:

```
	@XmlElement
	List<RestSememeVersion> versions;
```

As expected, I will get various generated Ruby classes including RestSememeChronology, RestSememeVersion, and, the various subclasses of  RestSememeVersion.  In  particular, I will get a ruby class called RestSememeDescriptionVersion.

Now consider the following json snippet (expressed in yaml format for clarity):
```
expandables:
sememeSequence: 1996127
assemblageSequence: 63
referencedComponentNid: -2146983539
identifiers:
  uuids:
  - 55657d7a-1cdd-39ec-bc07-f2f779433783
versions:
- "@class": gov.vha.isaac.rest.api1.data.sememe.RestSememeDescriptionVersion_**
  expandables:
    items:
    - name: chronology
      url: rest/1/sememe/chronology/1996127
    - name: nestedSememes
      url: rest/1/sememe/version/1996127/?expand=nestedSememes
...
  text: HEA (body structure)
``` 

If I ask my Ruby class RestSememeChronology to convert the json into a plain old Ruby object of type RestSememeChronology via the class method from_json the @class data (shown in the json above) is ignored.  For example, the generated Ruby code might look like:
```
class RestSememeChronology
#code omitted for brevity
    #initializes this RestSememeChronology with a json hash
     def init_jaxb_json_hash(_o)
	   #some code omitted for brevity
	   if !_o['versions'].nil?
       @versions = Array.new
       _oa = _o['versions']
       _oa.each { |_item|
       @versions.push Gov::Vha::Isaac::Rest::Api1::Data::Sememe::RestSememeVersion.from_json(_item)
     }
	 end
end
```

To patch the code I did the following:
```
class RestSememeChronology
#code omitted for brevity
    #initializes this RestSememeChronology with a json hash
     def init_jaxb_json_hash(_o)
	   #some code omitted for brevity
	   if !_o['versions'].nil?
       @versions = Array.new
       _oa = _o['versions']
       _oa.each { |_item|
	      clazz_array_parts = _item['@class'].split('.')
          short_clazz = clazz_array_parts.pop
          clazz_package = clazz_array_parts.map(&:capitalize).join("::")
          clazz = clazz_package + "::" + short_clazz
          @versions.push Object.const_get(clazz).send(:from_json, _item)
          #@versions.push Gov::Vha::Isaac::Rest::Api1::Data::Sememe::RestSememeVersion.from_json(_item)
     }
	 end
end
```

If I do not ensure that the @class portion of the json is used, as demonstrated above, then all inherited fields are inaccessible.
Note that I am using JsonTypeInfo.Id.CLASS as opposed to JsonTypeInfo.Id.MINIMAL_CLASS.  If minimal class is allowed I am unsure that 
patching the generated file is even possible.

Is it possible to have enunciate generate code that consistently uses the type information sent with the JSON?

Thanks,

Cris
